ignore:
  - "external"
  - "external_imported"
  - "src/base/WinsockContext.hpp"
  - "src/htm" # HTM not tested yet
  - "src/terminal/ParseConfigFile.hpp"
  - "src/terminal/TelemetryService*"
  - "src/terminal/PsuedoTerminalConsole.hpp"
  - "src/terminal/PsuedoUserTerminal.hpp"
  - "src/terminal/*Main.cpp"
  - "src/base/TcpSocketHandler*"
  - "src/base/SubprocessToString*"
coverage:
  status:
    project:
      default:
        target: 50%
