#!/bin/bash

SSH_COMMAND=$1
HOSTNAME=$2
PORT=$3
SERVER_BINARY="ETServer"
CLIENT_BINARY="ETClient"

PASSWORD_GENERATOR="env LC_CTYPE=C tr -dc \"a-zA-Z0-9\" < /dev/urandom | head -c 32"
SSH_PASSWORD_COMMAND="
export TMPFILE=\$(mktemp /tmp/et.XXXXXX) &&
export PASSWD=\`$PASSWORD_GENERATOR\` &&
echo \$PASSWD > \$TMPFILE &&
echo PASSWORD:\$PASSWD &&
$SERVER_BINARY --v=9 --alsologtostderr --passkeyfile=\$TMPFILE --port=$PORT --daemon=true
"
PASSWD=`echo "$SSH_PASSWORD_COMMAND" | ssh "$SSH_COMMAND" | grep PASSWORD: | cut -d: -f2`

TMPFILE=$(mktemp /tmp/et.XXXXXX)
echo $PASSWD > $TMPFILE

$CLIENT_BINARY --passkeyfile=$TMPFILE --v=9 --host="$HOSTNAME" --port="$PORT" --log_dir=$PWD
