#!/bin/bash

SSH_COMMAND=$1
HOSTNAME=$2
PORT=$3
SERVER_BINARY="TerminalServer"
CLIENT_BINARY="TerminalClient"

PASSWORD_GENERATOR="env LC_CTYPE=C tr -dc \"a-zA-Z0-9\" < /dev/urandom | head -c 32"
SSH_PASSWORD_COMMAND="echo \`$PASSWORD_GENERATOR\`"
PASSWD=`echo "$SSH_PASSWORD_COMMAND" | ssh "$SSH_COMMAND"`

SSH_SERVER_COMMAND="setsid $SERVER_BINARY --v=1 --alsologtostderr --passkey=$PASSWD --port=$PORT </dev/zero &>/dev/null &"
ssh "$SSH_COMMAND" "$SSH_SERVER_COMMAND"

$CLIENT_BINARY --passkey="$PASSWD" --v=1 --host="$HOSTNAME" --port="$PORT"
