#!/bin/bash

PORT="2022"
USER=${USER}
ET_COMMAND=""
SSH_COMMAND=""
TMP_DIR=${TMPDIR:-${TMP:-${TEMP:-/tmp}}}
LOG_DIR=$TMP_DIR
VERBOSITY=""

for i in "$@"
do
    case $i in
        -s=*|--ssh=*)
            SSH_COMMAND="${i#*=}"
            shift
            ;;
        -p=*|--port=*)
            PORT="${i#*=}"
            shift
            ;;
        -u=*|--user=*)
            USER="${i#*=}"
            shift
            ;;
        -l=*|--logdir=*)
            LOG_DIR="${i#*=}"
            shift
            ;;
        -v)
            VERBOSITY="--v=9"
            shift
            ;;
        -h|--help)
            printf "et (options) [user@]hostname[:port]

Options:
-h Basic usage
-s Special ssh command if necessary, otherwise set to user@hostname:22
-p Port for etserver to run on.  Don't set to the same port as ssh.  Default: 2022
-u Username to connect to ssh & ET
-l Directory where log files will go
-v verbose log files
"
            exit 0
            ;;
        *)
            ET_COMMAND="${i}"
            ;;
    esac
done

ET_COMMAND_REGEX="^(([0-9a-zA-Z]+)@)?([^\/:?@#]+)(:([0-9]+))?$"

if [[ $ET_COMMAND =~ $ET_COMMAND_REGEX ]]; then
    ET_USER="${BASH_REMATCH[2]}"
    ET_HOSTNAME="${BASH_REMATCH[3]}"
    ET_PORT="${BASH_REMATCH[5]}"
    if [[ -n "$ET_USER" ]]; then
        USER=$ET_USER
    fi
    if [[ -n "$ET_HOSTNAME" ]]; then
        HOSTNAME=$ET_HOSTNAME
    fi
    if [[ -n "$ET_PORT" ]]; then
        PORT=$ET_PORT
    fi
else
    printf "Usage: ET (options) [user@]hostname[:port]\n"
    exit 1
fi

if [[ -z "$SSH_COMMAND" ]]; then
    # Assume we want to bring the user into the ssh command but not
    # the port.
    SSH_COMMAND=${USER}@${HOSTNAME}
fi

SERVER_BINARY="etserver"
CLIENT_BINARY="etclient"

PASSWORD_GENERATOR="env LC_ALL=C tr -dc \"a-zA-Z0-9\" < /dev/urandom | head -c 32"
ID_GENERATOR=${PASSWORD_GENERATOR}
TMPFILE=$(mktemp "$TMP_DIR"/et-client.XXXXXXXXXXXX)
SSH_PASSWORD_COMMAND="
export SERVER_TMP_DIR=\${TMPDIR:-\${TMP:-\${TEMP:-/tmp}}}
export TMPFILE=\$(mktemp \"\$SERVER_TMP_DIR\"/et-server.XXXXXXXXXXXX)
PASSWORD=\$($PASSWORD_GENERATOR)
ID=\$($ID_GENERATOR)
echo \$PASSWORD
echo \$ID
printf \"%s/%s\\n\" \"\$ID\" \"\$PASSWORD\" > \"\${TMPFILE}\"
$SERVER_BINARY --idpasskeyfile=\"\${TMPFILE}\" && printf \"PASSWORD:%s/%s\\n\" \"\$ID\" \"\$PASSWORD\"
"
(printf "%s\n" "$SSH_PASSWORD_COMMAND" | ssh -T $SSH_COMMAND '/bin/bash' | grep PASSWORD: | cut -d: -f2) > ${TMPFILE}

$CLIENT_BINARY --idpasskeyfile="$TMPFILE" $VERBOSITY --host="$HOSTNAME" --port="$PORT" --log_dir="$LOG_DIR" 2> /tmp/etclient_err
