# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "debian/buster64"
  config.ssh.shell = "sh"

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 8
  end

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.
  config.vm.provision "file", source: "../id_rsa.pub", destination: ".ssh/id_rsa.pub"
  config.vm.provision "file", source: "../id_rsa", destination: ".ssh/id_rsa"
  config.vm.provision "file", source: "../.gnupg", destination: ".gnupg"
  config.vm.provision "file", source: "build_all_deb.sh", destination: "build_all_deb.sh"
  config.vm.provision "file", source: "debian_SOURCE", destination: "debian_SOURCE"

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", privileged: true, inline: <<-SHELL
  apt update
  DEBIAN_FRONTEND=noninteractive DEBIAN_PRIORITY=critical apt -q -y -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold" upgrade
  apt install -y build-essential git curl devscripts aptly dput jq libsodium-dev libprotobuf-dev protobuf-compiler cmake libutempter-dev debhelper git-lfs dh-systemd pbuilder ubuntu-dev-tools openssh-server qemu qemu-user-static debootstrap binfmt-support
SHELL

  config.vm.provision "shell", privileged: false, inline: <<-SHELL

  git config --global user.email "jgmath2000@gmail.com"
  git config --global user.name "Jason Gauci"

  sudo chmod -R 0700 ~/.gnupg ~/.ssh
  git lfs install
  
  echo "PBUILDERSATISFYDEPENDSCMD=/usr/lib/pbuilder/pbuilder-satisfydepends-apt" > ~/.pbuilderrc
  echo "default-cache-ttl 34560000
max-cache-ttl 34560000" > ~/.gnupg/gpg-agent.conf
  
  ssh-keyscan github.com >> ~/.ssh/known_hosts
  git clone --branch release git@github.com:MisterTea/EternalTerminal.git
  git clone git@github.com:MisterTea/debian-et.git
  
  for distro in `distro-info --supported | grep -v experimental`; do
    pbuilder-dist ${distro} i386 create --debootstrapopts --variant=buildd
    pbuilder-dist ${distro} amd64 create --debootstrapopts --variant=buildd
    pbuilder-dist ${distro} armhf create --debootstrapopts --variant=buildd
    pbuilder-dist ${distro} armel create --debootstrapopts --variant=buildd
    pbuilder-dist ${distro} arm64 create --debootstrapopts --variant=buildd

    aptly repo create -distribution=${distro} -component=main et-${distro}
  done

SHELL
end
