coverage:
  status:
    project:
      default:
        informational: true
    patch: false

comment:
  layout: "diff"
  require_changes: true
  after_n_builds: 3 # linux llvm-cov, linux kcov, mac llvm-cov
